### ISSUE TITLE
Need more data when actions fire

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-hold-button#1]
Awesome project!!

When including multiple buttons on a single page, it is important to distinguish between them when an action fires.  It will be nice if you can pass parameters when using the component.

```
{{#hold-button type="rectangle" action="move" model}}
  Hold to Move Question
{{/hold-button}}
```

**Comment by chrissloey** [comment]
Thanks :)

Done, update to 0.2.0. I think you might need to pass `model` as the first argument, like so:

```
{{#hold-button model type="rectangle" action="move"}}
  Hold to Move Question
{{/hold-button}}
```

**Comment by friksa** [comment]
Awesome!!  Works like a charm!!  Thank you

**Comment by caseyjenks** [comment]
And this addon gets even better!
