### ISSUE TITLE
Does not work on the iPad

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-hold-button#2]
This project is perfect to get rid of modal confirmations on mobile devices... except it does not seem to work on mobile devices.  Using the iOS emulator with iPad 2, when you hold the button, it selects the text on it and there is no animation or action triggered.

```
{{#hold-button value attribute type="rectangle" action="moveSelected"}}
```

**Comment by chrissloey** [comment]
Just to confirm - is this using 0.3.1? There was no support for touch events etc until then. I wasn't able to reproduce.

**Comment by friksa** [comment]
My apologies.  You are moving too fast.  I did not realize that you snucked another release in there.  It is all working as advertised.

Great job!!

**Comment by chrissloey** [comment]
Great thanks :smile:
