### ISSUE TITLE
Supplying a model to the action

### ISSUE THREAD

**Issue by jackmatt2** [AddJam/ember-hold-button#4]
It would be great if you could supply a parameter to the action like you can is a regular action.

``` html
{{#each items as |item|}}
  {{item.name}}
  <button {{action 'delete' item}}>Delete</button>
{{/each}}
```

**Comment by chrissloey** [comment]
You can already do this :smile:

From readme:

> You can also pass arguments to the component which will then be passed to the action.
> 
> ```
> {{hold-button model action="save" type="rectangle"}}
> ```

**Comment by jackmatt2** [comment]
Oh yeah, :+1:
